import type { Song, Genre, Lyrics } from "./types"

// Sample genres
export const genres: Genre[] = [
  {
    id: "pop",
    name: "Pop",
    coverUrl: "/genre covers/pop.jpg",
  },
  {
    id: "rock",
    name: "Rock",
    coverUrl: "/genre covers/rock.jpeg",
  },
  {
    id: "hiphop",
    name: "Hip Hop",
    coverUrl: "/placeholder.svg?height=300&width=300", // Add a hip hop cover image
  },
  {
    id: "electronic",
    name: "Electronic",
    coverUrl: "/genre covers/electronic.jpeg",
  },
  {
    id: "rnb",
    name: "R&B",
    coverUrl: "/genre covers/r&b.jpeg",
  },
]

// Real songs from the public folder
export const songs: Song[] = [
  {
    id: "blinding-lights",
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "pop",
    coverUrl: "/covers for songs/blinding lights.jpg",
    audioUrl: "/songs/Starboy.mp3", // Using Starboy as a replacement since blinding lights isn't available
    duration: 203,
  },
  {
    id: "die-for-you",
    title: "Die For You",
    artist: "The Weeknd",
    genre: "pop",
    coverUrl: "/covers for songs/die for you.jpeg",
    audioUrl: "/songs/die-for-you.mp3",
    duration: 219,
  },
  {
    id: "starboy",
    title: "Starboy",
    artist: "The Weeknd",
    genre: "pop",
    coverUrl: "/covers for songs/starboy.jpg",
    audioUrl: "/songs/Starboy.mp3",
    duration: 230,
  },
  {
    id: "montero",
    title: "Montero",
    artist: "Lil Nas X",
    genre: "hiphop",
    coverUrl: "/covers for songs/montero.png",
    audioUrl: "/songs/montero.mp3",
    duration: 178,
  },
  {
    id: "as-it-was",
    title: "As It Was",
    artist: "Harry Styles",
    genre: "pop",
    coverUrl: "/covers for songs/as it was.jpeg",
    audioUrl: "/songs/as-it-was.mp3",
    duration: 167,
  },
  {
    id: "kill-bill",
    title: "Kill Bill",
    artist: "SZA",
    genre: "rnb",
    coverUrl: "/covers for songs/kill bill.jpg",
    audioUrl: "/songs/kill-bill.mp3",
    duration: 153,
  },
  {
    id: "moonlight",
    title: "Moonlight",
    artist: "XXXTENTACION",
    genre: "hiphop",
    coverUrl: "/covers for songs/moonlight.jpeg",
    audioUrl: "/songs/moonlight.mp3",
    duration: 135,
  },
  {
    id: "paint-the-town-red",
    title: "Paint The Town Red",
    artist: "Doja Cat",
    genre: "hiphop",
    coverUrl: "/covers for songs/paint town.jpg",
    audioUrl: "/songs/paint-the-town-red.mp3",
    duration: 232,
  },
  {
    id: "levitating",
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "pop",
    coverUrl: "/covers for songs/levitating.webp",
    audioUrl: "/songs/levitating.mp3",
    duration: 203,
  },
  {
    id: "let-me-love-you",
    title: "Let Me Love You",
    artist: "DJ Snake ft. Justin Bieber",
    genre: "electronic",
    coverUrl: "/covers for songs/let me love you.jpg",
    audioUrl: "/songs/let-me-love-you.mp3",
    duration: 205,
  },
  {
    id: "love-nwantiti",
    title: "Love Nwantiti",
    artist: "CKay",
    genre: "rnb",
    coverUrl: "/covers for songs/love nwantiti.jpeg",
    audioUrl: "/songs/love-nwantiti.mp3",
    duration: 163,
  },
  {
    id: "i-wanna-be-yours",
    title: "I Wanna Be Yours",
    artist: "Arctic Monkeys",
    genre: "rock",
    coverUrl: "/covers for songs/i wanna be yours.jpeg",
    audioUrl: "/songs/die-for-you.mp3", // Placeholder since the actual song isn't in the folder
    duration: 183,
  },
  {
    id: "espresso",
    title: "Espresso",
    artist: "Sabrina Carpenter",
    genre: "pop",
    coverUrl: "/covers for songs/espresso.jpg",
    audioUrl: "/songs/espresso.mp3",
    duration: 142,
  },
  {
    id: "havana",
    title: "Havana",
    artist: "Camila Cabello",
    genre: "pop",
    coverUrl: "/covers for songs/havana.jpeg",
    audioUrl: "/songs/levitating.mp3", // Using levitating as a temporary replacement since we don't have the actual Havana audio file
    duration: 217,
  },
  {
    id: "finding-her",
    title: "Finding Her",
    artist: "JONY",
    genre: "pop",
    coverUrl: "/covers for songs/finding her.jpg",
    audioUrl: "/songs/finding-her.mp3",
    duration: 198,
  },
  {
    id: "paaro",
    title: "Paaro",
    artist: "Aaditya Rikhari",
    genre: "pop",
    coverUrl: "/covers for songs/paaro.jpeg",
    audioUrl: "/songs/paaro.mp3",
    duration: 210,
  },
  {
    id: "calm-down",
    title: "Calm Down",
    artist: "Rema",
    genre: "rnb",
    coverUrl: "/covers for songs/calm down.jpeg",
    audioUrl: "/songs/calm-down.mp3",
    duration: 239,
  },
  {
    id: "the-box",
    title: "The Box",
    artist: "Roddy Ricch",
    genre: "hiphop",
    coverUrl: "/covers for songs/the box.jpeg",
    audioUrl: "/songs/the-box.mp3",
    duration: 197,
  },
  {
    id: "main-phir-bhi",
    title: "Main Phir Bhi Tumko Chahunga",
    artist: "Arijit Singh",
    genre: "pop",
    coverUrl: "/covers for songs/main phir bhi tumko chahunga.jpg",
    audioUrl: "/songs/main-phir-bhi-tumko-chahunga.mp3",
    duration: 327,
  },
]

// Artist information
export const artists = [
  {
    id: "weeknd",
    name: "The Weeknd",
    coverUrl: "/artist covers/weeknd.jpeg",
    bio: "Abel Makkonen Tesfaye, known professionally as the Weeknd, is a Canadian singer, songwriter, and record producer."
  },
  {
    id: "dua-lipa",
    name: "Dua Lipa",
    coverUrl: "/artist covers/dua.jpg",
    bio: "Dua Lipa is an English singer and songwriter. Her musical career began at age 14, when she began covering songs by other artists on YouTube."
  },
  {
    id: "arctic-monkeys",
    name: "Arctic Monkeys",
    coverUrl: "/artist covers/artic.jpeg",
    bio: "Arctic Monkeys are an English rock band formed in Sheffield in 2002. The group consists of Alex Turner, Jamie Cook, Nick O'Malley, and Matt Helders."
  },
  {
    id: "ckay",
    name: "CKay",
    coverUrl: "/artist covers/ckay.jpeg",
    bio: "Chukwuka Ekweani, known professionally as CKay, is a Nigerian singer, songwriter and record producer."
  },
  {
    id: "aditya",
    name: "Aaditya Rikhari",
    coverUrl: "/artist covers/aditya.jpeg",
    bio: "Aaditya Rikhari is an Indian singer-songwriter known for his soulful voice and emotional compositions."
  },
  {
    id: "harry",
    name: "Harry Styles",
    coverUrl: "/artist covers/harry.webp",
    bio: "Harry Edward Styles is an English singer, songwriter and actor. His musical career began in 2010 as a solo contestant on the British music competition series The X Factor."
  },
  {
    id: "sza",
    name: "SZA",
    coverUrl: "/artist covers/sza.jpg",
    bio: "Solána Imani Rowe, known professionally as SZA, is an American singer and songwriter."
  }
]

// Developer information
export const developers = [
  {
    name: "Aakash Sarang",
    role: "Developer",
    image: "/img developer images/me.jpg",
    bio: "Pursuing BTech CSE from Jagran Lakecity University.",
    links: {
      github: "https://github.com",
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com"
    }
  },
  {
    name: "Nisha Kushwaha",
    role: "Developer",
    image: "/placeholder.svg?height=200&width=200", // Placeholder image
    bio: "Pursuing BTech CSE from Jagran Lakecity University.",
    links: {
      github: "https://github.com",
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com"
    }
  }
]

// Sample lyrics with actual lyrics from the files
export const lyricsData: Record<string, Lyrics> = {
  "blinding-lights": [
    { time: 0, text: "Yeah" },
    { time: 3, text: "I've been tryna call" },
    { time: 6, text: "I've been on my own for long enough" },
    { time: 9, text: "Maybe you can show me how to love, maybe" },
    { time: 12, text: "I'm going through withdrawals" },
    { time: 15, text: "You don't even have to do too much" },
    { time: 18, text: "You can turn me on with just a touch, baby" },
    { time: 21, text: "I look around and Sin City's cold and empty" },
    { time: 24, text: "No one's around to judge me" },
    { time: 27, text: "I can't see clearly when you're gone" },
    { time: 30, text: "I said, ooh, I'm blinded by the lights" },
    { time: 33, text: "No, I can't sleep until I feel your touch" },
    { time: 36, text: "I said, ooh, I'm drowning in the night" },
    { time: 39, text: "Oh, when I'm like this, you're the one I trust" },
    { time: 42, text: "Hey, hey, hey" },
    { time: 45, text: "I'm running out of time" },
    { time: 48, text: "'Cause I can see the sun light up the sky" },
    { time: 51, text: "So I hit the road in overdrive, baby" },
    { time: 54, text: "Oh, the city's cold and empty" },
    { time: 57, text: "No one's around to judge me" },
    { time: 60, text: "I can't see clearly when you're gone" },
  ],
  "starboy": [
    { time: 0, text: "I'm tryna put you in the worst mood, ah" },
    { time: 5, text: "P1 cleaner than your church shoes, ah" },
    { time: 10, text: "Milli point two just to hurt you, ah" },
    { time: 15, text: "All red Lamb' just to tease you, ah" },
    { time: 20, text: "None of these toys on lease too, ah" },
    { time: 25, text: "Made your whole year in a week too, yeah" },
    { time: 30, text: "Main bitch out your league too, ah" },
    { time: 35, text: "Side bitch out of your league too, ah" },
    { time: 40, text: "House so empty, need a centerpiece" },
    { time: 45, text: "Twenty racks a table cut from ebony" },
    { time: 50, text: "Cut that ivory into skinny pieces" },
    { time: 55, text: "Then she clean it with her face man I love my baby" },
  ],
  "levitating": [
    { time: 0, text: "If you wanna run away with me, I know a galaxy" },
    { time: 5, text: "And I can take you for a ride" },
    { time: 10, text: "I had a premonition that we fell into a rhythm" },
    { time: 15, text: "Where the music don't stop for life" },
    { time: 20, text: "Glitter in the sky, glitter in my eyes" },
    { time: 25, text: "Shining just the way I like" },
    { time: 30, text: "If you're feeling like you need a little bit of company" },
    { time: 35, text: "You met me at the perfect time" },
    { time: 40, text: "You want me, I want you, baby" },
    { time: 45, text: "My sugarboo, I'm levitating" },
    { time: 50, text: "The Milky Way, we're renegading" },
    { time: 55, text: "Yeah, yeah, yeah, yeah, yeah" },
  ],
  "havana": [
    { time: 0, text: "Hey" },
    { time: 4, text: "Havana, ooh-na-na (ay)" },
    { time: 8, text: "Half of my heart is in Havana, ooh-na-na (ay, ay)" },
    { time: 12, text: "He took me back to East Atlanta, na-na-na, ah" },
    { time: 16, text: "Oh, but my heart is in Havana (ay)" },
    { time: 20, text: "There's somethin' 'bout his manners (uh-huh), Havana, ooh-na-na (uh)" },
    { time: 24, text: "He didn't walk up with that, \"How you doin'?\" (Uh)" },
    { time: 28, text: "When he came in the room" },
    { time: 32, text: "He said there's a lotta girls I can do with (uh)" },
    { time: 36, text: "But I can't without you" },
    { time: 40, text: "I knew him forever in a minute (hey)" },
    { time: 44, text: "That summer night in June" },
    { time: 48, text: "And papa says he got malo in him (uh)" },
    { time: 52, text: "He got me feelin' like, \"Ooh, ooh, ooh-ooh\" (ay)" },
    { time: 56, text: "I knew it when I met him (ay), I loved him when I left him" },
    { time: 60, text: "Got me feelin' like, \"Ooh, ooh, ooh-ooh\"" },
    { time: 64, text: "And then I had to tell him, I had to go" },
    { time: 68, text: "Oh, na-na-na-na-na (whoo)" },
    { time: 72, text: "Havana, ooh-na-na (ay, ay)" },
    { time: 76, text: "Half of my heart is in Havana, ooh-na-na (ay, ay, uh-huh)" },
    { time: 80, text: "He took me back to East Atlanta, na-na-na" },
    { time: 84, text: "Oh, but my heart is in Havana (huh)" },
    { time: 88, text: "My heart is in Havana (hey), Havana, ooh-na-na" },
  ],
  "die-for-you": [
    { time: 0, text: "I'm finding ways to stay concentrated on what I feel" },
    { time: 5, text: "Oh, I'm trying to hide but I'm still reminded" },
    { time: 10, text: "I'm finding ways to stay concentrated on what I feel" },
    { time: 15, text: "Oh, I'm trying to hide but I'm still reminded of the pain" },
    { time: 20, text: "I'm finding ways to manipulate my sense of smell" },
    { time: 25, text: "And I'm trying to distinguish between the feelings I have" },
    { time: 30, text: "I'm finding ways to manipulate my sense of smell" },
    { time: 35, text: "And I'm trying to distinguish between the feelings I have" },
    { time: 40, text: "I die for you" },
    { time: 45, text: "I lie for you" },
    { time: 50, text: "I die for you" },
    { time: 55, text: "I lie for you" },
    { time: 60, text: "I die for you" },
    { time: 65, text: "I lie for you" },
  ],
  "as-it-was": [
    { time: 0, text: "Come on, Harry, we wanna say goodnight to you" },
    { time: 5, text: "Holdin' me back, gravity's holdin' me back" },
    { time: 10, text: "I want you to hold out the palm of your hand" },
    { time: 15, text: "Why don't we leave it at that?" },
    { time: 20, text: "Nothin' to say and everything gets in the way" },
    { time: 25, text: "Seems you cannot be replaced" },
    { time: 30, text: "And I'm the one who will stay, oh" },
    { time: 35, text: "In this world, it's just us" },
    { time: 40, text: "You know it's not the same as it was" },
    { time: 45, text: "In this world, it's just us" },
    { time: 50, text: "You know it's not the same as it was" },
    { time: 55, text: "As it was, as it was" },
    { time: 60, text: "You know it's not the same" },
  ],
  "kill-bill": [
    { time: 0, text: "I'm still a fan even though I was salty" },
    { time: 5, text: "Hate to see you with some other broad, know you happy" },
    { time: 10, text: "Hate to see you happy if I'm not the one driving" },
    { time: 15, text: "I'm so mature, I'm so mature" },
    { time: 20, text: "I'm so mature, I got me a therapist to tell me there's other men" },
    { time: 25, text: "I don't want none, I just want you" },
    { time: 30, text: "If I can't have you, no one should" },
    { time: 35, text: "I might kill my ex, not the best idea" },
    { time: 40, text: "His new girlfriend's next, how'd I get here?" },
    { time: 45, text: "I might kill my ex, I still love him though" },
    { time: 50, text: "Rather be in jail than alone" },
    { time: 55, text: "I did it all for love (love)" },
    { time: 60, text: "I did it all on no drugs (drugs)" },
  ],
  "moonlight": [
    { time: 0, text: "Spotlight, uh, moonlight, uh" },
    { time: 3, text: "Nigga, why you trippin'? Get your mood right, uh" },
    { time: 6, text: "Shawty look good in the moonlight" },
    { time: 9, text: "All these pussy niggas so bad mind" },
    { time: 12, text: "Spotlight, moonlight" },
    { time: 15, text: "Nigga, why you trippin'? Get your mood right" },
    { time: 18, text: "Shawty look good in the moonlight" },
    { time: 21, text: "All these pussy niggas so bad mind" },
    { time: 24, text: "Spotlight, uh, moonlight" },
    { time: 27, text: "Nigga, why you trippin'? Get your mood right, uh" },
    { time: 30, text: "Shawty look good in the moonlight" },
    { time: 33, text: "All these pussy niggas so bad mind" },
    { time: 36, text: "Feel like I'm destined, I don't need no Smith & Wesson, no" },
    { time: 39, text: "Boy, who you testin'? Fuck a Scantron, here's your lesson, oh" },
    { time: 42, text: "Knife in intestine, takin' shots with all your brethren, no" },
    { time: 45, text: "Feel like I'm damaged, girl I know you fuckin' planned this" },
    { time: 48, text: "Girl you threw my heart in the garbage" },
    { time: 51, text: "I'm livin' life so tragic, yeah" },
  ],
  "paint-the-town-red": [
    { time: 0, text: "Yeah, ah" },
    { time: 3, text: "Bitch, I said I'm sorry, I'm sorry" },
    { time: 6, text: "I ain't sorry for shit, fuck that" },
    { time: 9, text: "I said I'm sorry, I'm sorry" },
    { time: 12, text: "I ain't sorry for shit, I lied" },
    { time: 15, text: "I said I'm sorry, I'm sorry" },
    { time: 18, text: "I ain't sorry for shit, fuck that" },
    { time: 21, text: "I said I'm sorry, I'm sorry" },
    { time: 24, text: "I ain't sorry for shit" },
    { time: 27, text: "That's that bipolar shit" },
    { time: 30, text: "That's that up and down, round and round shit" },
    { time: 33, text: "That's that all night long, can't put my phone down shit" },
    { time: 36, text: "That's that I don't wanna talk, leave me alone shit" },
    { time: 39, text: "Paint the town red, bitch, paint the town red" },
    { time: 42, text: "Paint the town red, bitch, paint the town red" },
    { time: 45, text: "I'm 'bout to paint the town red, bitch" },
    { time: 48, text: "Paint the town red, bitch, paint the town red" },
    { time: 51, text: "Paint the town red, bitch, paint the town red" },
    { time: 54, text: "I'm 'bout to paint the town red, bitch" },
  ],
  "espresso": [
    { time: 0, text: "I'm working late 'cause I'm a big girl" },
    { time: 5, text: "I do what I want when I want and if I want it" },
    { time: 10, text: "Then I got it, yeah, I'm selfish" },
    { time: 15, text: "Hate waitin' on help, I'd rather do it myself" },
    { time: 20, text: "I've been on my own since seventeen" },
    { time: 25, text: "I'm a big girl, I do what I want when I want it" },
    { time: 30, text: "And I'm picky, so I'm choosy when I want it" },
    { time: 35, text: "Yeah, I like my men like I like my coffee" },
    { time: 40, text: "Sweet like sugar, with a little bit of cream" },
    { time: 45, text: "I'm his favorite flavor, I'm his favorite flavor" },
    { time: 50, text: "He can't get enough of me" },
    { time: 55, text: "I'm his espresso, I'm his espresso" },
    { time: 60, text: "He ain't never had it this strong" },
  ],
  "let-me-love-you": [
    { time: 0, text: "I used to believe" },
    { time: 5, text: "We were burnin' on the edge of somethin' beautiful" },
    { time: 10, text: "Somethin' beautiful" },
    { time: 15, text: "Sellin' a dream" },
    { time: 20, text: "Smoke and mirrors keep us waitin' on a miracle" },
    { time: 25, text: "On a miracle" },
    { time: 30, text: "Say, go through the darkest of days" },
    { time: 35, text: "Heaven's a heartbreak away" },
    { time: 40, text: "Never let you go, never let me down" },
    { time: 45, text: "Oh, it's been a hell of a ride" },
    { time: 50, text: "Driving the edge of a knife" },
    { time: 55, text: "Never let you go, never let me down" },
    { time: 60, text: "Don't you give up, nah, nah, nah" },
  ],
  "calm-down": [
    { time: 0, text: "Baby, calm down, calm down" },
    { time: 3, text: "Girl, this your body e put my heart for lockdown" },
    { time: 6, text: "For lockdown, oh, lockdown" },
    { time: 9, text: "Girl, you sweet like Fanta, ooh" },
    { time: 12, text: "If I tell you say \"I love you\", no dey form yanga, oh" },
    { time: 15, text: "No tell me say \"You love me, you love me, you love me, oh\"" },
    { time: 18, text: "When I see you, I wan' marry, marry, marry you, oh" },
    { time: 21, text: "Girl, you too fine, you too fine for my eye, oh" },
    { time: 24, text: "You too sweet, you too sweet for my belle, oh" },
    { time: 27, text: "Baby, calm down, calm down" },
    { time: 30, text: "Girl, this your body e put my heart for lockdown" },
    { time: 33, text: "For lockdown, oh, lockdown" },
    { time: 36, text: "Girl, you sweet like Fanta, ooh" },
    { time: 39, text: "Another day, another night" },
    { time: 42, text: "You dey my mind, oh baby" },
    { time: 45, text: "I no go lie, I need you in my life, yeah" },
    { time: 48, text: "Baby, calm down, calm down" },
    { time: 51, text: "Girl, this your body e put my heart for lockdown" },
    { time: 54, text: "For lockdown, oh, lockdown" },
    { time: 57, text: "Girl, you sweet like Fanta, ooh" },
  ],
  "i-wanna-be-yours": [
    { time: 0, text: "I wanna be your vacuum cleaner" },
    { time: 5, text: "Breathing in your dust" },
    { time: 10, text: "I wanna be your Ford Cortina" },
    { time: 15, text: "I will never rust" },
    { time: 20, text: "If you like your coffee hot" },
    { time: 25, text: "Let me be your coffee pot" },
    { time: 30, text: "You call the shots, babe" },
    { time: 35, text: "I just wanna be yours" },
    { time: 40, text: "Secrets I have held in my heart" },
    { time: 45, text: "Are harder to hide than I thought" },
    { time: 50, text: "Maybe I just wanna be yours" },
    { time: 55, text: "I wanna be yours, I wanna be yours" },
    { time: 60, text: "Wanna be yours, wanna be yours, wanna be yours" },
  ],
  "montero": [
    { time: 0, text: "Daytrip took it to ten (Hey)" },
    { time: 3, text: "I caught it bad yesterday" },
    { time: 6, text: "You hit me with a call to your place" },
    { time: 9, text: "Ain't been out in a while anyway" },
    { time: 12, text: "Was hoping I could catch you throwin' smiles in my face" },
    { time: 15, text: "Romantic talkin'? You don't even have to try" },
    { time: 18, text: "You're cute enough to fuck with me tonight" },
    { time: 21, text: "Lookin' at the table and I see the reason why" },
    { time: 24, text: "Baby, you livin' the life, but nigga, you ain't livin' right" },
    { time: 27, text: "Cocaine and drinking with your friends" },
    { time: 30, text: "You live in the dark, boy, I cannot pretend" },
    { time: 33, text: "I'm not fazed, only here to sin" },
    { time: 36, text: "If Eve ain't in your garden, you know that you can" },
    { time: 39, text: "Call me when you want, call me when you need" },
    { time: 42, text: "Call me in the morning, I'll be on the way" },
    { time: 45, text: "Call me when you want, call me when you need" },
    { time: 48, text: "Call me out by your name, I'll be on the way like" },
    { time: 51, text: "Mmm, mmm, mmm" },
    { time: 54, text: "Mmm, mmm, mmm" },
  ],
  "finding-her": [
    { time: 0, text: "I was lost" },
    { time: 3, text: "In the darkness of my soul" },
    { time: 6, text: "I was blind" },
    { time: 9, text: "Couldn't see beyond my nose" },
    { time: 12, text: "Then she came" },
    { time: 15, text: "Like a ray of golden light" },
    { time: 18, text: "Showed me love" },
    { time: 21, text: "That I never knew was right" },
    { time: 24, text: "Finding her was like finding myself" },
    { time: 27, text: "Finding her was like finding hope" },
    { time: 30, text: "Finding her was all that I needed" },
    { time: 33, text: "Finding her was coming back home" },
    { time: 36, text: "Now I see" },
    { time: 39, text: "All the colors of the world" },
    { time: 42, text: "Now I feel" },
    { time: 45, text: "All the beauty life unfurled" },
    { time: 48, text: "She's the one" },
    { time: 51, text: "Who has captured all my heart" },
    { time: 54, text: "She's my love" },
    { time: 57, text: "Never want to be apart" },
  ],
  "paaro": [
    { time: 0, text: "Paaro, paaro, paaro" },
    { time: 3, text: "Tere bina jeena kya" },
    { time: 6, text: "Tere bina jeena kya" },
    { time: 9, text: "Paaro, paaro, paaro" },
    { time: 12, text: "Tere bina marna kya" },
    { time: 15, text: "Tere bina marna kya" },
    { time: 18, text: "Paaro, paaro, paaro" },
    { time: 21, text: "Tu jo nahi hai toh" },
    { time: 24, text: "Kuch bhi nahi hai" },
    { time: 27, text: "Jeevan safar mein" },
    { time: 30, text: "Tu hi toh hamraahi hai" },
    { time: 33, text: "Paaro, paaro, paaro" },
    { time: 36, text: "Tere bina jeena kya" },
    { time: 39, text: "Tere bina jeena kya" },
    { time: 42, text: "Paaro, paaro, paaro" },
    { time: 45, text: "Tere bina marna kya" },
    { time: 48, text: "Tere bina marna kya" },
    { time: 51, text: "Paaro, paaro, paaro" },
    { time: 54, text: "Tu jo nahi hai toh" },
    { time: 57, text: "Kuch bhi nahi hai" },
  ],
}

export function getLyrics(songId: string): Lyrics | null {
  return lyricsData[songId] || null
}
